import { Exercise01 } from "./exercise01/exercise01";
import { Exercise02 } from "./exercise02/exercise02";
import { Exercise03 } from "./exercise03/exercise03";
import { Exercise04 } from "./exercise04/exercise04";
import { Exercise05 } from "./exercise05/exercise05";
import { Exercise07 } from "./exercise07/exercise07";
import { Exercise08 } from "./exercise08/exercise08";
import { Exercise09 } from "./exercise09/exercise09";
import { Exercise10 } from "./exercise10/exercise10";

new Exercise01().start();
// new Exercise02().start();
// new Exercise03().start();
// new Exercise04().start();
// new Exercise05().start();
// new Exercise06().start();
// new Exercise07().start();
// new Exercise08().start();
// new Exercise09().start();
// new Exercise10().start();